### PR TITLE
Merged master and resolve conflicts

### PR DESCRIPTION
**Pull request by nyurik**
Thanks for working on cargo-toml formatting, this PR should help move it along as it seems like it stalled a bit

### CODE REVIEW

**Comment by xxchan** [comment]
Thanks!

**Comment by xxchan** [comment]
I havn't run into cases like this before. How should I review/merge such a PR? 🤔

**Comment by xxchan** [comment]
Wow, I found `git show 91543f0c` did the trick! (credit to https://haacked.com/archive/2014/02/21/reviewing-merge-commits/)

It seems you updated too much `Cargo.lock`. I guess you deleted the whole file and regenerated it. You should `git checkout --theirs` instead to make minimal changes.

**Comment by xxchan** [comment]
https://github.com/rust-lang/rustfmt/pull/5240#issuecomment-1668519350

**Comment by nyurik** [comment]
already merged as part of xxchan/cargo_edit

**Pull request closed without merging**
